MoradSurvivorRules = MoradSurvivorRules or {}

local MSR = MoradSurvivorRules

MSR.Config = {
    DebugLogging = true,

    ModData = {
        StarterApplied = "MSR_StarterSkills_Applied_CraftingV3",
        ContinuityApplied = "MSR_Continuity_Applied",
        LastEatTime = "MSR_LastEatTime",
        ProteinScore24h = "MSR_ProteinScore24h",
        ProteinContributions = "MSR_ProteinContributions",
        ProteinEffective = "MSR_ProteinEffective",
        FreshContributions = "MSR_FreshContributions",
        FreshEffective = "MSR_FreshEffective",
        ComfortContributions = "MSR_ComfortContributions",
        ComfortEffective = "MSR_ComfortEffective",
        PoorDietContributions = "MSR_PoorDietContributions",
        PoorDietEffective = "MSR_PoorDietEffective",
        FreshScore24h = "MSR_FreshScore24h",
        PoorDietScore24h = "MSR_PoorDietScore24h",
        ProteinFedExpire = "MSR_Buff_ProteinFed_Expire",
        FreshDietExpire = "MSR_Buff_FreshDiet_Expire",
        ComfortMealExpire = "MSR_Buff_ComfortMeal_Expire",
        PoorDietExpire = "MSR_PoorDiet_Expire",
        OverfullRefreshTime = "MSR_OverfullRefreshTime",
    },

    ServerModDataKey = "MoradSurvivorRules_Continuity",

    StarterSkills = {
        PerkFactory.Perks.Woodwork,
        PerkFactory.Perks.Cooking,
        PerkFactory.Perks.Farming,
        PerkFactory.Perks.Doctor,
        PerkFactory.Perks.Electricity,
        PerkFactory.Perks.MetalWelding,
        PerkFactory.Perks.Mechanics,
        PerkFactory.Perks.Tailoring,
        PerkFactory.Perks.FlintKnapping,
        PerkFactory.Perks.Masonry,
        PerkFactory.Perks.Pottery,
        PerkFactory.Perks.Carving,
        PerkFactory.Perks.Blacksmith,
        PerkFactory.Perks.Butchering,
        PerkFactory.Perks.Glassmaking,
    },

    VanillaSkills = {
        PerkFactory.Perks.Strength,
        PerkFactory.Perks.Fitness,
        PerkFactory.Perks.Sprinting,
        PerkFactory.Perks.Lightfoot,
        PerkFactory.Perks.Nimble,
        PerkFactory.Perks.Sneak,
        PerkFactory.Perks.Axe,
        PerkFactory.Perks.Blunt,
        PerkFactory.Perks.SmallBlunt,
        PerkFactory.Perks.LongBlade,
        PerkFactory.Perks.SmallBlade,
        PerkFactory.Perks.Spear,
        PerkFactory.Perks.Maintenance,
        PerkFactory.Perks.Woodwork,
        PerkFactory.Perks.Cooking,
        PerkFactory.Perks.Farming,
        PerkFactory.Perks.Doctor,
        PerkFactory.Perks.Electricity,
        PerkFactory.Perks.MetalWelding,
        PerkFactory.Perks.Mechanics,
        PerkFactory.Perks.Tailoring,
        PerkFactory.Perks.Aiming,
        PerkFactory.Perks.Reloading,
        PerkFactory.Perks.Fishing,
        PerkFactory.Perks.Trapping,
        PerkFactory.Perks.PlantScavenging,
        PerkFactory.Perks.FlintKnapping,
        PerkFactory.Perks.Masonry,
        PerkFactory.Perks.Pottery,
        PerkFactory.Perks.Carving,
        PerkFactory.Perks.Husbandry,
        PerkFactory.Perks.Tracking,
        PerkFactory.Perks.Blacksmith,
        PerkFactory.Perks.Butchering,
        PerkFactory.Perks.Glassmaking,
    },

    Food = {
        ProteinFedDurationHours = 12,
        FreshDietDurationHours = 18,
        ComfortMealDurationHours = 24,
        PoorDietDurationHours = 18,

        ProteinEffectPerPoint = 1.0,
        ProteinEffectMax = 60,
        ProteinEnduranceDeltaMax = 0.003,
        ProteinFatigueReductionDeltaMax = 0.0015,
        ProteinCarryWeightMax = 3,
        ContributionRampUpRatio = 0.25,
        ContributionPeakRatio = 0.35,
        ContributionDecayRatio = 0.40,
        FreshEffectPerPoint = 1.0,
        FreshEffectMax = 20,
        ComfortEffectPerPoint = 1.0,
        ComfortEffectMax = 20,
        PoorDietEffectPerPoint = 1.0,
        PoorDietEffectMax = 20,

        ComfortStressReduction = 0.05,
        ComfortUnhappinessReduction = 8,

        TickMinutes = 10,
        PassiveStressDelta = 0.004,
        PassiveUnhappinessDelta = 0.35,
        PassiveBoredomDelta = 0.45,
        PoorDietStressDelta = 0.003,
        PoorDietUnhappinessDelta = 0.2,
    },

    UI = {
        Enabled = false,
        UseHaloNotifications = true,
        NotificationCooldownHours = 0.05,
        X = 32,
        Y = 220,
        IconSize = 32,
        Gap = 6,
        Icons = {
            ProteinFed = "media/ui/MSR_ProteinFed.png",
            FreshDiet = "media/ui/MSR_FreshDiet.png",
            ComfortMeal = "media/ui/MSR_ComfortMeal.png",
            PoorDiet = "media/ui/MSR_PoorDiet.png",
        },
        Text = {
            ProteinFed = {
                Name = "Protein Fed / 蛋白充足",
                Desc = "蛋白摄入充足，身体状态良好，适合远征和清理区域。",
            },
            FreshDiet = {
                Name = "Fresh Diet / 新鲜饮食",
                Desc = "摄入了足够的新鲜食物，精神状态更稳定。",
            },
            ComfortMeal = {
                Name = "Comfort Meal / 暖心饭",
                Desc = "一顿好饭让你暂时忘记末日压力。",
            },
            PoorDiet = {
                Name = "Poor Diet / 糟糕饮食",
                Desc = "长期吃得太差，身体和精神状态都受到影响。",
            },
        },
    },
}
